DevCampOutput/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :posts
  root to: 'welcome#index'
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  devise_for :users, :path_prefix => 'd'
  resources :users do
    member do
      get :follow
      get :following
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

DevCampOutput/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

DevCampOutput/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

DevCampOutput/app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true

    def change
        create_table :relationships do |t|
          t.integer :follower_id
          t.integer :followed_id
     
          t.timestamps null: false
        end
        add_index :relationships, :follower_id
        add_index :relationships, :followed_id
        add_index :relationships, [:follower_id, :followed_id], unique: true
      end
end

DevCampOutput/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  def follow(other_user)
    following << other_user
  end
 
  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end
 
  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
  has_many :passive_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  #has_many :followed_users, through: :relationships, source: :followed

  
end

DevCampOutput/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

DevCampOutput/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new post_params

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :message)
    end
end

DevCampOutput/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    #before_action :logged_in_user
   
    def create
      @user = User.find(params[:followed_id])
      current_user.follow(@user)
      respond_to do |format|
        format.html { redirect_to @user }
        format.js
      end
      puts("CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCccs")

      redirect_back(fallback_location: root_path)
    end
   
    def destroy
      @user = Relationship.find(params[:id]).followed
      current_user.unfollow(@user)
      respond_to do |format|
        format.html { redirect_to @user }
        format.js
      end
      redirect_back(fallback_location: root_path)
    end
  end

DevCampOutput/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def show
    #@user = User.find_by_email(params[:id])
    @user = User.find params[:id]
    #@posts = Post.where user_id: params[:user_id]
    puts("BBBBBBBBBBBBBBBBBBBBBB")
    puts(@user.id)
    puts("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
  end

  def follow
    #@user = User.find_by_email(params[:id])
    if current_user.follow!(@user)
      redirect_to @user, notice: "Follow successful!"
    else 
      redirect_to @user, alert: "Error following."
    end
  end
end

DevCampOutput/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

DevCampOutput/app/helpers/application_helper.rb
module ApplicationHelper
end

DevCampOutput/app/helpers/posts_helper.rb
module PostsHelper
end

DevCampOutput/app/helpers/users_helper.rb
module UsersHelper
end

DevCampOutput/app/helpers/welcome_helper.rb
module WelcomeHelper
end

DevCampOutput/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevCampOutput</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

DevCampOutput/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

DevCampOutput/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

DevCampOutput/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.user.email, user_path(post.user.email)%></td>
        <td><%= post.message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<br>
<%= link_to 'Home', root_path %>

DevCampOutput/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

DevCampOutput/app/views/posts/show.html.erb
<p>
  <strong>User:</strong>
  <%= @post.user.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @post.message %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

DevCampOutput/app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

DevCampOutput/app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

DevCampOutput/app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to "Following", following_user_path(@user) %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  <%= link_to "Followers", followers_user_path(@user) %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
</div>

DevCampOutput/app/views/static_pages/profile.html.erb
<section class="stats">
        <%= render 'shared/stats' %>
      </section>

DevCampOutput/app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

DevCampOutput/app/views/users/_follow_form.html.erb
<% if !(current_user.equal?(@user)) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

DevCampOutput/app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

DevCampOutput/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% @users = User.all %>
<% @users.each do |user| %>
  <%= user.email %><br/>
<% end %>

DevCampOutput/app/views/users/show.html.erb
<p>
 <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  <%= @user.email%>
  <h2>Posts</h2>
  <% @user.posts.each do |post|  %>
      <li>
        <%= @user.email %>
        <%= post.message %>
      </li>

  <% end %>
  <%= render 'follow_form' if current_user %>
  <p><%= link_to "Back to Posts", posts_path %></p>
</p>

DevCampOutput/app/views/welcome/index.html.erb
<!DOCTYPE HTML>
<html lang = "en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- basic.html -->
    <title>basic.html</title>
    <meta charset = "UTF-8" />
</head>
<body>
    <h1>Welcome!</h1>
    <div class="jumbotron text-center">
  <h1>Devcamp Output</h1>
  <p>Ken Tabagan, Gab Datiles, JC Peroz</p>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-4">
    <% if !current_user %>
      <h3>Register/Sign in</h3>
      <p><%= link_to "Register", new_user_registration_path %></p>
      <p><%= link_to "Sign in", new_user_session_path %></p>
    <% else %>
      <h3>Sign out</h3>
      <p><%= link_to "Sign out", destroy_user_session_path, method: :delete %></p>
      <p><%= link_to "View posts", posts_path %></p>
    <% end %>
    </div>
  </div>
</div>
</body>
</html>